
CREATE TABLE IF NOT EXISTS public.company ( company_id uuid NOT NULL,
                                                            is_active boolean NOT NULL DEFAULT true,
                                                                                               is_deleted boolean NOT NULL DEFAULT false,
                                                                                                                                   tanent_id character varying(250) COLLATE pg_catalog."default",
                                                                                                                                                                            company_name character varying(250) COLLATE pg_catalog."default" NOT NULL,
                                                                                                                                                                                                                                             full_company_name character varying(250) COLLATE pg_catalog."default" NOT NULL,
                                                                                                                                                                                                                                                                                                                   logo_link character varying(250) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                            photos uuid[], registered_date date, gtm time with time zone,
                                                                                                                                                                                                                                                                                                                                                                                                                    company_phone character varying(100) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 fax character varying(100) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    website character varying(100) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           additional_url character varying(100) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         email character varying(150) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              employees character varying(50) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      founded_in integer, legal_form character varying(100) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    vat_uid character varying(100) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           dun character varying(100) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              linkedin character varying(200) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      twitter character varying(200) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             youtube character varying(200) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    instagram character varying(200) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             facebook character varying(200) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     industry character varying(200)[] COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               technology character varying(200)[] COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           metarial character varying(200)[] COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     process character varying(200)[] COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              password character varying(250) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      sector character varying(200)[] COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              CONSTRAINT company_pkey PRIMARY KEY (company_id)) TABLESPACE pg_default;


ALTER TABLE public.company OWNER to postgres;


CREATE TABLE IF NOT EXISTS public.media ( media_id uuid NOT NULL,
                                                        company_id uuid,
                                                        user_id uuid,
                                                        is_active boolean NOT NULL DEFAULT true,
                                                                                           is_deleted boolean NOT NULL DEFAULT false,
                                                                                                                               title character varying(250) COLLATE pg_catalog."default" NOT NULL,
                                                                                                                                                                                         type character varying(100) COLLATE pg_catalog."default",
                                                                                                                                                                                                                             description text COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                      video_url character varying(250) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                               ref character varying(100) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                  file json,
                                                                                                                                                                                                                                                                                                                                       CONSTRAINT media_pkey PRIMARY KEY (media_id)) TABLESPACE pg_default;


ALTER TABLE public.media OWNER to postgres;


CREATE TABLE IF NOT EXISTS public.parameter ( parameter_id uuid NOT NULL,
                                                                is_active boolean NOT NULL DEFAULT true,
                                                                                                   is_deleted boolean NOT NULL DEFAULT false,
                                                                                                                                       name character varying(250) COLLATE pg_catalog."default" NOT NULL,
                                                                                                                                                                                                category character varying(100) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                        description text COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                 lang_id character varying(150) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                        char_value character varying(250) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                  int_value bigint, float_value real, bool_value boolean, json_value json,
                                                                                                                                                                                                                                                                                                                                                                                                          CONSTRAINT parameter_pkey PRIMARY KEY (parameter_id)) TABLESPACE pg_default;


ALTER TABLE public.parameter OWNER to postgres;


CREATE TABLE IF NOT EXISTS public.role ( id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY
                                            (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1), name character varying(255) COLLATE pg_catalog."default",
                                                                                                                                              CONSTRAINT role_pkey PRIMARY KEY (id)) TABLESPACE pg_default;


ALTER TABLE public.role OWNER to postgres;


CREATE TABLE IF NOT EXISTS public."user" ( id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY
                                              (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1), user_id uuid NOT NULL,
                                                                                                                         name character varying(255) COLLATE pg_catalog."default",
                                                                                                                                                             email character varying(255) COLLATE pg_catalog."default" NOT NULL,
                                                                                                                                                                                                                       username character varying(255) COLLATE pg_catalog."default" NOT NULL,
                                                                                                                                                                                                                                                                                    password character varying(255) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                            "passwordResetToken" character varying(255) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                "passwordResetExpires" timestamp with time zone,
                                                                                                                                                                                                                                                                                                                                                                                                                           phonenumber character varying(20) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     title character varying(255) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          location character varying(255) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  website character varying(255) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         picture character varying(255) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                facebook character varying(255) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        twitter character varying(255) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               google character varying(255) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     created_at timestamp with time zone,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    updated_at timestamp with time zone,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   isdeleted boolean, isactive boolean NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       user_role character varying(255) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                departman_id bigint, tenant_id uuid,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     company_id uuid,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     familyname character varying(100) COLLATE pg_catalog."default",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               CONSTRAINT user_pkey PRIMARY KEY (id), CONSTRAINT user_email_unique UNIQUE (email), CONSTRAINT user_username_unique UNIQUE (username)) TABLESPACE pg_default;


ALTER TABLE public.user OWNER to postgres;


CREATE TABLE IF NOT EXISTS public.user_roles
    ( "createdAt" timestamp without time zone NOT NULL,
                                              "updatedAt" timestamp without time zone NOT NULL,
                                                                                      "roleId" bigint NOT NULL,
                                                                                                      "userId" bigint NOT NULL,
                                                                                                                      CONSTRAINT user_roles_pkey PRIMARY KEY ("roleId",
                                                                                                                                                              "userId"), CONSTRAINT "user_roles_roleId_fkey"
     FOREIGN KEY ("roleId") REFERENCES public.role (id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE,
                                                                                                 CONSTRAINT "user_roles_userId_fkey"
     FOREIGN KEY ("userId") REFERENCES public."user" (id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE) TABLESPACE pg_default;


ALTER TABLE public.user_roles OWNER to postgres;


INSERT INTO public.role( id, name)
VALUES (1,
        'user');


INSERT INTO public.role( id, name)
VALUES (2,
        'moderator');


INSERT INTO public.role( id, name)
VALUES (3,
        'admin');